# Generated by Django 2.1.2 on 2018-11-01 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='评论者姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('personal_website', models.CharField(max_length=200, verbose_name='个人网站')),
                ('comment', models.TextField(verbose_name='评论')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.Post', verbose_name='文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
    ]
